
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/water?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:

mybatis:
  mapper-locations: "classpath*:mapper/**/*.xml"
server:
  port: 8802